---
title: "Cleaning Data"
format: html
editor: visual
---

### Clear workspace

```{r}
rm(list = ls())
```

### Import Packages

```{r}
#| message: false
library(tidyverse)
library(stringr)
library(dplyr)
```

### Load Data File

```{r}
#| message: false
data_load <- read_csv(file = '~/projects/Group25_Project/data/01_dat_load.csv')
data_path <- "~/projects/Group25_Project/data"
outfile_path <- file.path(data_path, '02_dat_clean.csv')
```

### Removing irrelevant columns

```{r}
cols_to_keep <-  c("barcode", "sample", "count.1", "log_fold_change", "p", "HLA", "Protein", "Peptide")
  
data_clean <- data_load|>
  select(all_of(cols_to_keep))
```

### Filtering significant subset

This drastically decreases the data load, from 35000+ observations to \~1000.

```{r}
data_clean <- data_clean |>
  filter(p < 0.001 & log_fold_change > 2)|>
  arrange(desc(log_fold_change))
```

### Extract information from sample column

```{r}
data_clean <- data_clean |>
  mutate(KIR_blocking = factor(case_when(str_detect(sample, "KIR") ~ "1",
                                         TRUE ~ "0"),
                               levels = c("1", "0")),
         double_positive = factor(case_when(str_detect(sample, "KIR_DP") ~ "1",
                                         TRUE ~ "0"),
                               levels = c("1", "0")),
         .after = sample,) |>
  separate_wider_delim("sample",
                       delim = "_",
                       names = c("sample_ID"),
                       too_many = "drop")

```

### Extract information from protein column

```{r}
data_clean <- data_clean |>
  mutate(Protein =
           factor(
             case_when(
               str_detect(Protein, "QHD43415_1") ~ "ORF1",
               str_detect(Protein, "QHD43423_2") ~ "Nucleocapsid",
               str_detect(Protein, "QHD43416_1") ~ "Spike", #surface
               str_detect(Protein, "QHD43420_1") ~ "ORF6",
               str_detect(Protein, "QHD43419_1") ~ "Membrane",
               str_detect(Protein, "QHD43417_1") ~ "ORF3",
               str_detect(Protein, "QHD43421_1") ~ "ORF7",
               str_detect(Protein, "QHD43418_1") ~ "Envelope",
               str_detect(Protein, "QHI42199_1") ~ "ORF10",
               str_detect(Protein, "QHD43422_1") ~ "ORF8",
               .default = "Unknown"),
             levels = c("ORF1", "Nucleocapsid", "Spike", "ORF6", "Membrane", "ORF3",
                        "ORF7", "Envelope", "ORF10", "ORF8", "Unknown" )))
```

### Renaming all column names for consistency

```{r}
data_clean <- data_clean |>
  rename(protein = Protein,
         count = "count.1",
         peptide = Peptide
         )
```

### Export data

```{r}
write_csv(data_clean, outfile_path)
```
