---
title: "03_describe"
format: html
editor: visual
---

## Prepping

```{r}
#| message: false

rm(list = ls())

library(tidyverse)
library("table1")
```

### Load Data

```{r}
#| message: false
data_b <- read_rds(file = '~/projects/Group25_Project/data/02_dat_clean_barracoda.RDS')
data_f <- read_rds(file = '~/projects/Group25_Project/data/02_dat_clean_flowjo.RDS')
data_p <- read_rds(file = '~/projects/Group25_Project/data/03_dat_aug_sig_pairing.RDS')
```

# Tables

### Barracoda

```{r}

summary_table <- data_b |>
                table1( x = formula(~ KIR_blocking + log_fold_change+protein + HLA| cohort),
                        data = _)

saveRDS(summary_table, file = "../results/tableOne_b.RDS")
summary_table

```

### FlowJo

```{r}

summary_table_f <-  data_f |>
                    mutate(APC_positive = APC_positive*100,    # in percent
                           DP_positive = DP_positive*100,      # in percent
                           PE_positive = PE_positive*100) |>   # in percent
                    mutate(KIR_blocking = factor(KIR_blocking, levels = c(1, 0),
                                                 labels = c("KIR-blocked",
                                                            "Not KIR-blocked"))) |>
              table1(x = formula(~ APC_positive + DP_positive + PE_positive | KIR_blocking),
                           data = _)

saveRDS(summary_table, file = "../results/tableOne_f.RDS")

summary_table_f
```

# Descriptive Plots

### Protein count distribution

Kan det passe at det bare er antal af rækker vi kigger på, og ikke count eller noget andet??

```{r}

protein_stack <- data_b |>
  group_by(HLA, protein) %>%
  count(name = "count_prot") %>%
  group_by(HLA) %>%
  mutate(relative_prot_count = (count_prot / sum(count_prot) ) * 100) |>
  ungroup() |>
  ggplot(aes(fill = protein, 
             y = relative_prot_count, 
             x = HLA)) + 
  geom_bar( position="stack",
            width = 0.3,
            stat="identity") + 
  theme_minimal()+
  labs( x = element_blank(),
      	y ='% of peptides',
        title = 'Distribution of SARS-Cov9 Genome Proteins',
      	fill = 'Protein',
      	caption = 'S. K. Saini et al., Sci. Immunol. 10.1126/sciimmunol.abf7550 (2021)')

protein_stack
```

### Barracoda

```{r}
#| message: false
# Prepare relevant data
data_counts <-  data_p |> 
  count(cohort, sample_ID, KIR_blocking)

# visual settings
color_1 <- "#69b3a2"
color_2 <- "grey"
text_size <- 14
dot_size <- 0.5
boxplot_width <- 0.6

# plotting
ggplot(data_counts, 
       aes(x = cohort, 
           y = n, 
           fill = KIR_blocking)) + 
      geom_jitter(size=dot_size, 
                  shape=1) +
      geom_violin(width = boxplot_width,
                   alpha = 0.8)+
      geom_boxplot(width = boxplot_width,
                   alpha = 0.2)+
      scale_fill_manual(values=c(color_1, color_2)) +
      theme_minimal(base_size = text_size)+
      theme(legend.position = 'right')+
    	labs( x='Cohort',
        		y='Count (n)',
        		title = 'Total Significante Respons Count per Sample',
        		subtitle ='2023',
        	  fill = 'KIR Blocking',
        		caption = 'S. K. Saini et al., Sci. Immunol. 10.1126/sciimmunol.abf7550 (2021)')

ggsave("../results/Boxplot_Nb_Responses.png")
```

## 

### FlowJo

```{r}
test <- data_p  |> filter(paired == 1) |>
          mutate(APC_positive = APC_positive*100,     
                           DP_positive = DP_positive*100,   
                           PE_positive = PE_positive*100) |>
          pivot_longer(
                     cols = c('PE_positive', 'APC_positive'),
                     names_to = 'Staining', 
                     values_to = 'Fraction') |>
        select(Fraction, Staining, sample_ID, cohort) |>
        unique()
test
```

```{r}

ggplot(test, 
       aes(x = Staining, 
           y = Fraction)) +
      facet_wrap(~cohort, scales='free_y')+
      geom_boxplot(width = boxplot_width,
                   alpha = 0.2)+
      geom_jitter(size= 1, 
                  shape= 1) +
      scale_fill_manual(values=c(color_1, color_2)) +
      theme_minimal(base_size = text_size)+
      theme(legend.position = 'bottom')+
    	labs( x=element_blank(),
        		y='% multimer CD8+ T-cells',
        		title = 'Write a clever observation here',
        		subtitle ='2023',
        	  fill = 'KIR Blocking',
        		caption = 'data from xx')
```

## Un-paired samples

```{r}
unpaired <- data_p  |>
            mutate(APC_positive = APC_positive*100,     
                             DP_positive = DP_positive*100,   
                             PE_positive = PE_positive*100) |>
            pivot_longer(
                       cols = c('PE_positive', 'APC_positive'),
                       names_to = 'Staining', 
                       values_to = 'Fraction') |>
          select(Fraction, Staining, sample_ID, cohort) |>
          unique()

ggplot(unpaired, 
       aes(x = Staining, 
           y = Fraction)) +
      facet_wrap(~cohort,
                 scales='free_y')+
      geom_boxplot(width = boxplot_width,
                   alpha = 0.2)+
      geom_jitter(size=dot_size, 
                  shape=1, ) +
      scale_fill_manual(values=c(color_1,
                                 color_2)) +
      theme_minimal(base_size = text_size)+
      theme(legend.position = 'bottom')+
    	labs( x=element_blank(),
        		y='% multimer CD8+ T-cells',
        		title = 'Write a clever observation here',
        		subtitle ='2023',
        	  fill = 'KIR Blocking',
        		caption = 'data from xx')
```
